name: sensor.flo
description: Flo water monitoring and control system
type: component
keywords:
  - flo
  - water
author:
  name: Ryan Snodgrass
  email: rsnodgrass@gmail.com
  homepage: https://github.com/rsnodgrass
license: Apache 2.0
files:
- custom_components/flo/sensor.py
- custom_components/flo/switch.py
