- platform: ip2sl
  host: <itach_ip_address>
  port: 4999 # which serial port to connect to (4999 = serial port 1)
  name: "Xantech Amplifier"
  commands:
    - name: "Power Off"
      data: "!AO+"

- platform: ip2sl
  host: <itach_ip_address>
  port: 4999 # which serial port to connect to (4999 = serial port 1)
  name: "Xantech Zone 1"
  commands:
    - name: "Power On"
      data: "!1PR1+"
    - name: "Power Off"
      data: "!1PR0+"
    - name: "Power Toggle"
      data: "!1PT+"
    - name: "Volume Up"
      data: "!1VI+"
    - name: "Volume Down"
      data: "!1VD+"
    - name: "Mute"
      data: "!1MU1+"
    - name: "Mute Off"
      data: "!1MU0+"
    - name: "Select Source 1"
      data: "!1SS1+"
    - name: "Select Source 2"
      data: "!1SS2+"
    - name: "Select Source 3"
      data: "!1SS3+"
    - name: "Select Source 4"
      data: "!1SS4+"
    - name: "Select Source 5"
      data: "!1SS5+"
    - name: "Select Source 6"
      data: "!1SS6+"
    - name: "Select Source 7"
      data: "!1SS7+"
    - name: "Select Source 8"
      data: "!1SS8+"

- platform: ip2sl
  host: <itach_ip_address>
  port: 4999 # which serial port to connect to (4999 = serial port 1)
  name: "Xantech Zone 2"
  commands:
    - name: "On"
      data: "!2PR1+"
    - name: "Off"
      data: "!2PR0+"
    - name: "Power Toggle"
      data: "!2PT+"
    - name: "Volume Up"
      data: "!2VI+"
    - name: "Volume Down"
      data: "!2VD+"
    - name: "Mute On"
      data: "!2MU1+"
    - name: "Mute Off"
      data: "!2MU0+"
    - name: "Select Source 1"
      data: "!2SS1+"
    - name: "Select Source 2"
      data: "!2SS2+"
    - name: "Select Source 3"
      data: "!2SS3+"
    - name: "Select Source 4"
      data: "!2SS4+"
    - name: "Select Source 5"
      data: "!2SS5+"
    - name: "Select Source 6"
      data: "!2SS6+"
    - name: "Select Source 7"
      data: "!2SS7+"
    - name: "Select Source 8"
      data: "!2SS8+"
