- platform: ip2sl
  host: <itach_ip_address>
  port: 4999 # which serial port to connect to (4999 = serial port 1)
  name: "Xantech Amplifier"
  commands:
    power_off:
      name: "Power Off"
      data: "!AO+"

- platform: ip2sl
  host: <itach_ip_address>
  port: 4999 # which serial port to connect to (4999 = serial port 1)
  name: "Xantech Zone 1"
  commands:
    power_on
      name: "Power On"
      data: "!1PR1+"
    power_off:
      name: "Power Off"
      data: "!1PR0+"
    power_toggle
      name: "Power Toggle"
      data: "!1PT+"
    volume_up:
      name: "Volume Up"
      data: "!1VI+"
    volume_down:
      name: "Volume Down"
      data: "!1VD+"
    mute:
      name: "Mute"
      data: "!1MU1+"
    mute_off:
      name: "Mute Off"
      data: "!1MU0+"
    select_source_1:
      name: "Select Source 1"
      data: "!1SS1+"
    select_source_2:
      name: "Select Source 2"
      data: "!1SS2+"
    select_source_3:
      name: "Select Source 3"
      data: "!1SS3+"
    select_source_4:
      name: "Select Source 4"
      data: "!1SS4+"
    select_source_5:
      name: "Select Source 5"
      data: "!1SS5+"
    select_source_6:
      name: "Select Source 6"
      data: "!1SS6+"
    select_source_7:
      name: "Select Source 7"
      data: "!1SS7+"
    select_source_8:
      name: "Select Source 8"
      data: "!1SS8+"


- platform: ip2sl
  host: <itach_ip_address>
  port: 4999 # which serial port to connect to (4999 = serial port 1)
  name: "Xantech Zone 2"
  commands:
    power_on
      name: "Power On"
      data: "!2PR1+"
    power_off:
      name: "Power Off"
      data: "!2PR0+"
    power_toggle
      name: "Power Toggle"
      data: "!2PT+"
    volume_up:
      name: "Volume Up"
      data: "!2VI+"
    volume_down:
      name: "Volume Down"
      data: "!2VD+"
    mute:
      name: "Mute"
      data: "!2MU1+"
    mute_off:
      name: "Mute Off"
      data: "!2MU0+"
    select_source_1:
      name: "Select Source 1"
      data: "!2SS1+"
    select_source_2:
      name: "Select Source 2"
      data: "!2SS2+"
    select_source_3:
      name: "Select Source 3"
      data: "!2SS3+"
    select_source_4:
      name: "Select Source 4"
      data: "!2SS4+"
    select_source_5:
      name: "Select Source 5"
      data: "!2SS5+"
    select_source_6:
      name: "Select Source 6"
      data: "!2SS6+"
    select_source_7:
      name: "Select Source 7"
      data: "!2SS7+"
    select_source_8:
      name: "Select Source 8"
      data: "!2SS8+"

